services:
  - type: web
    name: portfolio-backend
    env: node
    # TODO: upgrade to starter to avoid cold-start
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: FRONTEND_URL
        sync: false
